export const NLB_STOPS = [
  {
    stopId: "1",
    stopName_c: "梅窩碼頭",
    stopName_s: "梅窝码头",
    stopName_e: "Mui Wo Ferry Pier",
    stopLocation_c: "梅窩碼頭",
    stopLocation_s: "梅窝码头",
    stopLocation_e: "Mui Wo Ferry Pier",
    latitude: "22.26466400",
    longitude: "114.00155400",
  },
  {
    stopId: "10",
    stopName_c: "太古職員宿舍",
    stopName_s: "太古职员宿舍",
    stopName_e: "Swire Staff Holiday House",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.25191800",
    longitude: "113.98488700",
  },
  {
    stopId: "100",
    stopName_c: "東薈城",
    stopName_s: "东薈城",
    stopName_e: "Citygate",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.29013600",
    longitude: "113.94147400",
  },
  {
    stopId: "101",
    stopName_c: "松逸街",
    stopName_s: "松逸街",
    stopName_e: "Chung Yat Street",
    stopLocation_c: "松逸街",
    stopLocation_s: "松逸街",
    stopLocation_e: "Chung Yat Street",
    latitude: "22.27616400",
    longitude: "113.93182300",
  },
  {
    stopId: "102",
    stopName_c: "松滿路",
    stopName_s: "松满路",
    stopName_e: "Chung Mun Road",
    stopLocation_c: "松滿路",
    stopLocation_s: "松满路",
    stopLocation_e: "Chung Mun Road",
    latitude: "22.27720100",
    longitude: "113.93170000",
  },
  {
    stopId: "103",
    stopName_c: "逸東邨福逸樓",
    stopName_s: "逸东邨福逸楼",
    stopName_e: "Fuk Yat House, Yat Tung Estate",
    stopLocation_c: "裕東路",
    stopLocation_s: "裕东路",
    stopLocation_e: "Yu Tung Road",
    latitude: "22.27921600",
    longitude: "113.93465100",
  },
  {
    stopId: "104",
    stopName_c: "逸東邨雍逸樓",
    stopName_s: "逸东邨雍逸楼",
    stopName_e: "Yung Yat House, Yat Tung Estate",
    stopLocation_c: "裕東路",
    stopLocation_s: "裕东路",
    stopLocation_e: "Yu Tung Road",
    latitude: "22.27959200",
    longitude: "113.93671200",
  },
  {
    stopId: "105",
    stopName_c: "東涌港鐵站",
    stopName_s: "东涌港铁站",
    stopName_e: "Tung Chung MTR Station",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.28961300",
    longitude: "113.94021000",
  },
  {
    stopId: "106",
    stopName_c: "東涌發展碼頭",
    stopName_s: "东涌发展码头",
    stopName_e: "Tung Chung Development Ferry Pier",
    stopLocation_c: "東涌海濱路",
    stopLocation_s: "东涌海滨路",
    stopLocation_e: "Tung Chung Waterfront Road",
    latitude: "22.29384600",
    longitude: "113.94044900",
  },
  {
    stopId: "107",
    stopName_c: "海堤灣畔",
    stopName_s: "海堤湾畔",
    stopName_e: "Seaview Crescent",
    stopLocation_c: "惠東路",
    stopLocation_s: "惠东路",
    stopLocation_e: "Wai Tung Road",
    latitude: "22.29292500",
    longitude: "113.94347100",
  },
  {
    stopId: "108",
    stopName_c: "藍天海岸",
    stopName_s: "蓝天海岸",
    stopName_e: "Coastal Skyline",
    stopLocation_c: "文東路",
    stopLocation_s: "文东路",
    stopLocation_e: "Man Tung Road",
    latitude: "22.29094200",
    longitude: "113.94593100",
  },
  {
    stopId: "109",
    stopName_c: "映灣園二期",
    stopName_s: "映湾园二期",
    stopName_e: "Caribbean Coast Phase 2",
    stopLocation_c: "文東路",
    stopLocation_s: "文东路",
    stopLocation_e: "Man Tung Road",
    latitude: "22.29188200",
    longitude: "113.95001000",
  },
  {
    stopId: "11",
    stopName_c: "貝澳油站",
    stopName_s: "贝澳油站",
    stopName_e: "Pui O Petrol Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24731100",
    longitude: "113.98098500",
  },
  {
    stopId: "110",
    stopName_c: "健東路",
    stopName_s: "健东路",
    stopName_e: "Kin Tung Road",
    stopLocation_c: "健東路",
    stopLocation_s: "健东路",
    stopLocation_e: "Kin Tung Road",
    latitude: "22.29322200",
    longitude: "113.94941000",
  },
  {
    stopId: "111",
    stopName_c: "怡東路",
    stopName_s: "怡东路",
    stopName_e: "Yi Tung Road",
    stopLocation_c: "文東路",
    stopLocation_s: "文东路",
    stopLocation_e: "Man Tung Road",
    latitude: "22.29094900",
    longitude: "113.94801200",
  },
  {
    stopId: "112",
    stopName_c: "怡文中學",
    stopName_s: "怡文中学",
    stopName_e: "E Wun Secondary School",
    stopLocation_c: "文東路",
    stopLocation_s: "文东路",
    stopLocation_e: "Man Tung Road",
    latitude: "22.29085000",
    longitude: "113.94461100",
  },
  {
    stopId: "114",
    stopName_c: "飛機燃料庫",
    stopName_s: "飞机燃料库",
    stopName_e: "Aviation Fuel Tank Farm",
    stopLocation_c: "觀景路",
    stopLocation_s: "观景路",
    stopLocation_e: "Scenic Road",
    latitude: "22.29358400",
    longitude: "113.93212900",
  },
  {
    stopId: "115",
    stopName_c: "國泰城",
    stopName_s: "国泰城",
    stopName_e: "Cathay City",
    stopLocation_c: "觀景路",
    stopLocation_s: "观景路",
    stopLocation_e: "Scenic Road",
    latitude: "22.29754600",
    longitude: "113.93281400",
  },
  {
    stopId: "116",
    stopName_c: "二號檢查閘",
    stopName_s: "二号检查闸",
    stopName_e: "Gate House No. 2",
    stopLocation_c: "暢連路",
    stopLocation_s: "畅连路",
    stopLocation_e: "Cheong Lin Road",
    latitude: "22.31053500",
    longitude: "113.93710700",
  },
  {
    stopId: "117",
    stopName_c: "機場(客運大樓)",
    stopName_s: "机场(客运大楼)",
    stopName_e: "Airport (Passenger Terminal Building)",
    stopLocation_c: "暢達路",
    stopLocation_s: "畅达路",
    stopLocation_e: "Cheong Tat Road",
    latitude: "22.31456900",
    longitude: "113.93661000",
  },
  {
    stopId: "118",
    stopName_c: "暢達路",
    stopName_s: "畅达路",
    stopName_e: "Cheong Tat Road",
    stopLocation_c: "暢達路",
    stopLocation_s: "畅达路",
    stopLocation_e: "Cheong Tat Road",
    latitude: "22.31623600",
    longitude: "113.93594800",
  },
  {
    stopId: "12",
    stopName_c: "老圍村",
    stopName_s: "老围村",
    stopName_e: "Lo Wai Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24425200",
    longitude: "113.97923600",
  },
  {
    stopId: "120",
    stopName_c: "富豪機場酒店",
    stopName_s: "富豪机场酒店",
    stopName_e: "Regal Airport Hotel",
    stopLocation_c: "暢達路",
    stopLocation_s: "畅达路",
    stopLocation_e: "Cheong Tat Road",
    latitude: "22.31943000",
    longitude: "113.93394200",
  },
  {
    stopId: "121",
    stopName_c: "赤鱲角南路",
    stopName_s: "赤鱲角南路",
    stopName_e: "Chek Lap Kok South Road",
    stopLocation_c: "赤鱲角南路",
    stopLocation_s: "赤鱲角南路",
    stopLocation_e: "Chek Lap Kok South Road",
    latitude: "22.29188300",
    longitude: "113.92825100",
  },
  {
    stopId: "122",
    stopName_c: "亞洲空運中心",
    stopName_s: "亚洲空运中心",
    stopName_e: "Asia Airfreight Terminal",
    stopLocation_c: "駿坪路",
    stopLocation_s: "骏坪路",
    stopLocation_e: "Chun Ping Road",
    latitude: "22.29606500",
    longitude: "113.92080600",
  },
  {
    stopId: "124",
    stopName_c: "機場空運中心",
    stopName_s: "机场空运中心",
    stopName_e: "Airport Freight Forwarding Centre",
    stopLocation_c: "駿坪路",
    stopLocation_s: "骏坪路",
    stopLocation_e: "Chun Ping Road",
    latitude: "22.29501600",
    longitude: "113.92332900",
  },
  {
    stopId: "125",
    stopName_c: "香港空運貨站",
    stopName_s: "香港空运货站",
    stopName_e: "HACTL",
    stopLocation_c: "駿運路",
    stopLocation_s: "骏运路",
    stopLocation_e: "Chun Wan Road",
    latitude: "22.29712400",
    longitude: "113.92978400",
  },
  {
    stopId: "126",
    stopName_c: "機場空運中心",
    stopName_s: "机场空运中心",
    stopName_e: "Airport Freight Forwarding Centre",
    stopLocation_c: "駿運路",
    stopLocation_s: "骏运路",
    stopLocation_e: "Chun Wan Road",
    latitude: "22.29500500",
    longitude: "113.92434000",
  },
  {
    stopId: "127",
    stopName_c: "紅磡 (紅鸞道)",
    stopName_s: "红磡 (红鸾道)",
    stopName_e: "Hung Hom (Hung Luen Road)",
    stopLocation_c: "紅磡灣紅鸞道",
    stopLocation_s: "红磡湾红鸾道",
    stopLocation_e: "Hung Hom Bay Hung Luen Road",
    latitude: "22.30141600",
    longitude: "114.18809200",
  },
  {
    stopId: "128",
    stopName_c: "尖東港鐵站",
    stopName_s: "尖东港铁站",
    stopName_e: "East Tsim Sha Tsui MTR Station",
    stopLocation_c: "梳士巴利道",
    stopLocation_s: "梳士巴利道",
    stopLocation_e: "Salisbury Road",
    latitude: "22.29479800",
    longitude: "114.17438000",
  },
  {
    stopId: "129",
    stopName_c: "九龍公園",
    stopName_s: "九龙公园",
    stopName_e: "Kowloon Park",
    stopLocation_c: "彌敦道",
    stopLocation_s: "弥敦道",
    stopLocation_e: "Nathan Road",
    latitude: "22.29872100",
    longitude: "114.17192800",
  },
  {
    stopId: "13",
    stopName_c: "新圍村",
    stopName_s: "新围村",
    stopName_e: "Sun Wai Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24347600",
    longitude: "113.97817800",
  },
  {
    stopId: "131",
    stopName_c: "太子港鐵站",
    stopName_s: "太子港铁站",
    stopName_e: "Prince Edward MTR Station",
    stopLocation_c: "彌敦道",
    stopLocation_s: "弥敦道",
    stopLocation_e: "Nathan Road",
    latitude: "22.32581600",
    longitude: "114.16787600",
  },
  {
    stopId: "132",
    stopName_c: "欽州街",
    stopName_s: "钦州街",
    stopName_e: "Yen Chow Street",
    stopLocation_c: "長沙灣道",
    stopLocation_s: "长沙湾道",
    stopLocation_e: "Cheung Sha Wan Road",
    latitude: "22.33129900",
    longitude: "114.16136900",
  },
  {
    stopId: "134",
    stopName_c: "元朗港鐵站",
    stopName_s: "元朗港铁站",
    stopName_e: "Yuen Long MTR Station",
    stopLocation_c: "朗日路",
    stopLocation_s: "朗日路",
    stopLocation_e: "Long Yat Road",
    latitude: "22.44615300",
    longitude: "114.03388800",
  },
  {
    stopId: "135",
    stopName_c: "又新街",
    stopName_s: "又新街",
    stopName_e: "Yau San Street",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44430800",
    longitude: "114.03125200",
  },
  {
    stopId: "136",
    stopName_c: "大棠路",
    stopName_s: "大棠路",
    stopName_e: "Tai Tong Road",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44435500",
    longitude: "114.02825500",
  },
  {
    stopId: "137",
    stopName_c: "元朗警署",
    stopName_s: "元朗警署",
    stopName_e: "Yuen Long Police Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44438300",
    longitude: "114.02408500",
  },
  {
    stopId: "138",
    stopName_c: "水邊村",
    stopName_s: "水边村",
    stopName_e: "Shui Pin Tsuen",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44440700",
    longitude: "114.02078100",
  },
  {
    stopId: "139",
    stopName_c: "元朗公園",
    stopName_s: "元朗公园",
    stopName_e: "Yuen Long Park",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44411700",
    longitude: "114.01901300",
  },
  {
    stopId: "14",
    stopName_c: "羅屋村",
    stopName_s: "罗屋村",
    stopName_e: "Lo Uk Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24319200",
    longitude: "113.97488500",
  },
  {
    stopId: "140",
    stopName_c: "朗邊",
    stopName_s: "朗边",
    stopName_e: "Long Bin",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44338600",
    longitude: "114.01479900",
  },
  {
    stopId: "141",
    stopName_c: "屏山",
    stopName_s: "屏山",
    stopName_e: "Ping Shan",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44167400",
    longitude: "114.01037800",
  },
  {
    stopId: "142",
    stopName_c: "新起村",
    stopName_s: "新起村",
    stopName_e: "San Hei Tsuen",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44001900",
    longitude: "114.00763600",
  },
  {
    stopId: "143",
    stopName_c: "灰沙圍",
    stopName_s: "灰沙围",
    stopName_e: "Fui Sha Wai",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.43851400",
    longitude: "114.00465400",
  },
  {
    stopId: "144",
    stopName_c: "大道村",
    stopName_s: "大道村",
    stopName_e: "Tai Tao Tsuen",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.43645100",
    longitude: "114.00145900",
  },
  {
    stopId: "145",
    stopName_c: "洪水橋輕鐵站",
    stopName_s: "洪水桥轻铁站",
    stopName_e: "Hung Shui Kiu LTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.43385800",
    longitude: "113.99775000",
  },
  {
    stopId: "146",
    stopName_c: "鍾屋村輕鐵站",
    stopName_s: "钟屋村轻铁站",
    stopName_e: "Chung Uk Tsuen LTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42967300",
    longitude: "113.99223500",
  },
  {
    stopId: "147",
    stopName_c: "亦園村",
    stopName_s: "亦园村",
    stopName_e: "Yick Yuen Tsuen",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42716800",
    longitude: "113.98972800",
  },
  {
    stopId: "148",
    stopName_c: "泥圍",
    stopName_s: "泥围",
    stopName_e: "Nai Wai",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42362300",
    longitude: "113.98679600",
  },
  {
    stopId: "149",
    stopName_c: "福亨村",
    stopName_s: "福亨村",
    stopName_e: "Fuk Hang Tsuen",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42236000",
    longitude: "113.98564000",
  },
  {
    stopId: "15",
    stopName_c: "牛坳園",
    stopName_s: "牛坳园",
    stopName_e: "Ngau Au Yuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24304100",
    longitude: "113.97254500",
  },
  {
    stopId: "150",
    stopName_c: "妙法寺",
    stopName_s: "妙法寺",
    stopName_e: "Miu Fat Buddhist Monastery",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42043900",
    longitude: "113.98387800",
  },
  {
    stopId: "151",
    stopName_c: "藍地輕鐵站",
    stopName_s: "蓝地轻铁站",
    stopName_e: "Lam Tei LTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.41832800",
    longitude: "113.98238500",
  },
  {
    stopId: "152",
    stopName_c: "深圳灣口岸",
    stopName_s: "深圳湾口岸",
    stopName_e: "Shenzhen Bay Port",
    stopLocation_c: "深圳灣口岸",
    stopLocation_s: "深圳湾口岸",
    stopLocation_e: "Shenzhen Bay Port",
    latitude: "22.49743300",
    longitude: "113.95050900",
  },
  {
    stopId: "153",
    stopName_c: "青磚圍",
    stopName_s: "青砖围",
    stopName_e: "Tsing Chuen Wai",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42245200",
    longitude: "113.98530500",
  },
  {
    stopId: "154",
    stopName_c: "泥圍輕鐵站",
    stopName_s: "泥围轻铁站",
    stopName_e: "Nai Wai LTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42364800",
    longitude: "113.98631300",
  },
  {
    stopId: "155",
    stopName_c: "塘坊村輕鐵站",
    stopName_s: "塘坊村轻铁站",
    stopName_e: "Tong Fong Tsuen LRT Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44021000",
    longitude: "114.00731200",
  },
  {
    stopId: "156",
    stopName_c: "屏山輕鐵站",
    stopName_s: "屏山轻铁站",
    stopName_e: "Ping Shan LRT Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44321600",
    longitude: "114.01293000",
  },
  {
    stopId: "157",
    stopName_c: "朗庭園",
    stopName_s: "朗庭园",
    stopName_e: "Villa By The Park",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44425900",
    longitude: "114.01818900",
  },
  {
    stopId: "158",
    stopName_c: "喜利徑",
    stopName_s: "喜利径",
    stopName_e: "Hi Lee Path",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44465400",
    longitude: "114.02580200",
  },
  {
    stopId: "159",
    stopName_c: "同樂街",
    stopName_s: "同乐街",
    stopName_e: "Tung Lok Street",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44462900",
    longitude: "114.02822500",
  },
  {
    stopId: "16",
    stopName_c: "散石灣中蘆",
    stopName_s: "散石湾中芦",
    stopName_e: "San Shek Wan 3 1/4 Milestone",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24124400",
    longitude: "113.96910500",
  },
  {
    stopId: "160",
    stopName_c: "谷亭街",
    stopName_s: "谷亭街",
    stopName_e: "Kuk Ting Street",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44457800",
    longitude: "114.03023000",
  },
  {
    stopId: "161",
    stopName_c: "元朗港鐵站",
    stopName_s: "元朗港铁站",
    stopName_e: "Yuen Long MTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.44618900",
    longitude: "114.03481600",
  },
  {
    stopId: "162",
    stopName_c: "天水圍 (天慈邨)",
    stopName_s: "天水围 (天慈邨)",
    stopName_e: "Tin Shui Wai (Tin Tsz Estate)",
    stopLocation_c: "天喜街",
    stopLocation_s: "天喜街",
    stopLocation_e: "Tin Hei Street",
    latitude: "22.45353600",
    longitude: "114.00711100",
  },
  {
    stopId: "163",
    stopName_c: "嘉湖海逸酒店",
    stopName_s: "嘉湖海逸酒店",
    stopName_e: "Harbour Plaza Resort City",
    stopLocation_c: "天恩路",
    stopLocation_s: "天恩路",
    stopLocation_e: "Tin Yan Road",
    latitude: "22.45860500",
    longitude: "114.00326000",
  },
  {
    stopId: "164",
    stopName_c: "天水圍市中心",
    stopName_s: "天水围市中心",
    stopName_e: "Tin Shui Wai Town Centre",
    stopLocation_c: "天恩路",
    stopLocation_s: "天恩路",
    stopLocation_e: "Tin Yan Road",
    latitude: "22.45849800",
    longitude: "114.00199400",
  },
  {
    stopId: "165",
    stopName_c: "嘉湖山莊翠湖居",
    stopName_s: "嘉湖山庄翠湖居",
    stopName_e: "Chestwood Court, Kingswood Villas",
    stopLocation_c: "天榮路",
    stopLocation_s: "天荣路",
    stopLocation_e: "Tin Wing Road",
    latitude: "22.45959500",
    longitude: "113.99998400",
  },
  {
    stopId: "166",
    stopName_c: "天瑞邨",
    stopName_s: "天瑞邨",
    stopName_e: "Tin Shui Estate",
    stopLocation_c: "天瑞路",
    stopLocation_s: "天瑞路",
    stopLocation_e: "Tin Shui Road",
    latitude: "22.45699400",
    longitude: "113.99885700",
  },
  {
    stopId: "167",
    stopName_c: "天水圍公園",
    stopName_s: "天水围公园",
    stopName_e: "Tin Shui Wai Park",
    stopLocation_c: "天瑞路",
    stopLocation_s: "天瑞路",
    stopLocation_e: "Tin Shui Road",
    latitude: "22.45455700",
    longitude: "114.00254300",
  },
  {
    stopId: "168",
    stopName_c: "天耀邨耀盛樓",
    stopName_s: "天耀邨耀盛楼",
    stopName_e: "Yiu Shing House, Tin Yiu Estate",
    stopLocation_c: "天湖路",
    stopLocation_s: "天湖路",
    stopLocation_e: "Tin Wu Road",
    latitude: "22.45222100",
    longitude: "114.00216500",
  },
  {
    stopId: "169",
    stopName_c: "天耀邨耀民樓",
    stopName_s: "天耀邨耀民楼",
    stopName_e: "Yiu Man House, Tin Yiu Estate",
    stopLocation_c: "天耀路",
    stopLocation_s: "天耀路",
    stopLocation_e: "Tin Yiu Road",
    latitude: "22.44955000",
    longitude: "114.00317400",
  },
  {
    stopId: "17",
    stopName_c: "散石灣村",
    stopName_s: "散石湾村",
    stopName_e: "San Shek Wan Village",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23892800",
    longitude: "113.96677200",
  },
  {
    stopId: "170",
    stopName_c: "天盛苑",
    stopName_s: "天盛苑",
    stopName_e: "Tin Shing Court",
    stopLocation_c: "屏廈路",
    stopLocation_s: "屏厦路",
    stopLocation_e: "Ping Ha Road",
    latitude: "22.44698800",
    longitude: "114.00279400",
  },
  {
    stopId: "171",
    stopName_c: "天水圍警署",
    stopName_s: "天水围警署",
    stopName_e: "Tin Shui Wai Police Station",
    stopLocation_c: "天耀路",
    stopLocation_s: "天耀路",
    stopLocation_e: "Tin Yiu Road",
    latitude: "22.45017100",
    longitude: "114.00250400",
  },
  {
    stopId: "172",
    stopName_c: "嘉湖山莊賞湖居",
    stopName_s: "嘉湖山庄赏湖居",
    stopName_e: "Sherwood Court, Kingswood Villas",
    stopLocation_c: "天湖路",
    stopLocation_s: "天湖路",
    stopLocation_e: "Tin Wu Road",
    latitude: "22.45255000",
    longitude: "114.00216900",
  },
  {
    stopId: "173",
    stopName_c: "天頌苑",
    stopName_s: "天颂苑",
    stopName_e: "Tin Chung Court",
    stopLocation_c: "天榮路",
    stopLocation_s: "天荣路",
    stopLocation_e: "Tin Wing Road",
    latitude: "22.45986400",
    longitude: "114.00007900",
  },
  {
    stopId: "174",
    stopName_c: "嘉湖山莊麗湖居",
    stopName_s: "嘉湖山庄丽湖居",
    stopName_e: "Lynwood Court, Kingswood Villas",
    stopLocation_c: "天城路",
    stopLocation_s: "天城路",
    stopLocation_e: "Tin Shing Road",
    latitude: "22.45893400",
    longitude: "114.00359200",
  },
  {
    stopId: "175",
    stopName_c: "嘉湖山莊景湖居",
    stopName_s: "嘉湖山庄景湖居",
    stopName_e: "Kenswood Court, Kingswood Villas",
    stopLocation_c: "天城路",
    stopLocation_s: "天城路",
    stopLocation_e: "Tin Shing Road",
    latitude: "22.45736400",
    longitude: "114.00579700",
  },
  {
    stopId: "176",
    stopName_c: "天水圍 (天耀邨)",
    stopName_s: "天水围 (天耀邨)",
    stopName_e: "Tin Shui Wai (Tin Yiu Estate)",
    stopLocation_c: "天耀路",
    stopLocation_s: "天耀路",
    stopLocation_e: "Tin Yiu Road",
    latitude: "22.45053000",
    longitude: "114.00302900",
  },
  {
    stopId: "178",
    stopName_c: "南大嶼山海底電纜站",
    stopName_s: "南大屿山海底电缆站",
    stopName_e: "South Lantau Sea Cable Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22527200",
    longitude: "113.92866100",
  },
  {
    stopId: "179",
    stopName_c: "東涌道",
    stopName_s: "东涌道",
    stopName_e: "Tung Chung Road",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23791800",
    longitude: "113.96292000",
  },
  {
    stopId: "18",
    stopName_c: "女青年會梁紹榮度假村",
    stopName_s: "女青年会梁绍荣度假村",
    stopName_e: "YWCA Sydney Leong Holiday Lodge",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23748400",
    longitude: "113.96400100",
  },
  {
    stopId: "180",
    stopName_c: "貝澳",
    stopName_s: "贝澳",
    stopName_e: "Pui O",
    stopLocation_c: "芝麻灣道",
    stopLocation_s: "芝麻湾道",
    stopLocation_e: "Chi Ma Wan Road",
    latitude: "22.24309100",
    longitude: "113.97712400",
  },
  {
    stopId: "181",
    stopName_c: "塘福",
    stopName_s: "塘福",
    stopName_e: "Tong Fuk",
    stopLocation_c: "塘福",
    stopLocation_s: "塘福",
    stopLocation_e: "Tong Fuk",
    latitude: "22.22761600",
    longitude: "113.93228900",
  },
  {
    stopId: "183",
    stopName_c: "奶路臣街",
    stopName_s: "奶路臣街",
    stopName_e: "Nelson Street",
    stopLocation_c: "彌敦道",
    stopLocation_s: "弥敦道",
    stopLocation_e: "Nathan Road",
    latitude: "22.31801800",
    longitude: "114.16951500",
  },
  {
    stopId: "184",
    stopName_c: "怡閣苑",
    stopName_s: "怡阁苑",
    stopName_e: "Yee Kok Court",
    stopLocation_c: "長沙灣道",
    stopLocation_s: "长沙湾道",
    stopLocation_e: "Cheung Sha Wan Road",
    latitude: "22.33389400",
    longitude: "114.15804300",
  },
  {
    stopId: "185",
    stopName_c: "北大嶼山醫院(北行), 逸東邨美逸樓",
    stopName_s: "北大屿山医院(北行), 逸东邨美逸楼",
    stopName_e:
      "North Lantau Hospital (North Bound), Mei Yat House Yat Tung Estate",
    stopLocation_c: "松仁路",
    stopLocation_s: "松仁路",
    stopLocation_e: "Chung Yan Road",
    latitude: "22.28129500",
    longitude: "113.93882200",
  },
  {
    stopId: "186",
    stopName_c: "映灣園三期",
    stopName_s: "映湾园三期",
    stopName_e: "Caribbean Coast Phase 3",
    stopLocation_c: "文東路",
    stopLocation_s: "文东路",
    stopLocation_e: "Man Tung Road",
    latitude: "22.29142400",
    longitude: "113.94897500",
  },
  {
    stopId: "187",
    stopName_c: "駿運南路",
    stopName_s: "骏运南路",
    stopName_e: "Chun Wan Road South",
    stopLocation_c: "駿運南路",
    stopLocation_s: "骏运南路",
    stopLocation_e: "Chun Wan Road South",
    latitude: "22.29631900",
    longitude: "113.92846900",
  },
  {
    stopId: "188",
    stopName_c: "北大嶼山醫院(主座大樓)",
    stopName_s: "北大屿山医院(主座大楼)",
    stopName_e: "North Lantau Hospital(Main Block)",
    stopLocation_c: "北大嶼山醫院急症室外",
    stopLocation_s: "北大屿山医院急症室外",
    stopLocation_e: "North Lantau Hospital, outside Casualty Ward",
    latitude: "22.28202800",
    longitude: "113.93926900",
  },
  {
    stopId: "19",
    stopName_c: "長沙上村",
    stopName_s: "长沙上村",
    stopName_e: "Cheung Sha Sheung Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23523800",
    longitude: "113.96173900",
  },
  {
    stopId: "190",
    stopName_c: "昇薈(北行)",
    stopName_s: "升薈(北行)",
    stopName_e: "The Visionary(North Bound)",
    stopLocation_c: "迎東路",
    stopLocation_s: "迎东路",
    stopLocation_e: "Ying Tung Road",
    latitude: "22.29582300",
    longitude: "113.95190700",
  },
  {
    stopId: "191",
    stopName_c: "昇薈(南行)",
    stopName_s: "升薈(南行)",
    stopName_e: "The Visionary (South Bound)",
    stopLocation_c: "迎東路",
    stopLocation_s: "迎东路",
    stopLocation_e: "Ying Tung Road",
    latitude: "22.29583500",
    longitude: "113.95207700",
  },
  {
    stopId: "192",
    stopName_c: "迎禧路",
    stopName_s: "迎禧路",
    stopName_e: "Ying Hei Road",
    stopLocation_c: "迎禧路",
    stopLocation_s: "迎禧路",
    stopLocation_e: "Ying Hei Road",
    latitude: "22.29431000",
    longitude: "113.94999600",
  },
  {
    stopId: "193",
    stopName_c: "迎東邨",
    stopName_s: "迎东邨",
    stopName_e: "Ying Tung Estate",
    stopLocation_c: "迎東邨",
    stopLocation_s: "迎东邨",
    stopLocation_e: "Ying Tung Estate",
    latitude: "22.29710400",
    longitude: "113.95334200",
  },
  {
    stopId: "194",
    stopName_c: "映灣園一期",
    stopName_s: "映湾园一期",
    stopName_e: "Caribbean Coast Phase 1",
    stopLocation_c: "文東路",
    stopLocation_s: "文东路",
    stopLocation_e: "Man Tung Road",
    latitude: "22.29349500",
    longitude: "113.95181600",
  },
  {
    stopId: "195",
    stopName_c: "亦園村",
    stopName_s: "亦园村",
    stopName_e: "Yick Yuen Tsuen",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42739600",
    longitude: "113.99036600",
  },
  {
    stopId: "196",
    stopName_c: "藍地輕鐵站",
    stopName_s: "蓝地轻铁站",
    stopName_e: "Lam Tei LTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.41844400",
    longitude: "113.98214600",
  },
  {
    stopId: "197",
    stopName_c: "灰沙圍",
    stopName_s: "灰沙围",
    stopName_e: "Fui Sha Wai",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.43866900",
    longitude: "114.00540400",
  },
  {
    stopId: "199",
    stopName_c: "大道村",
    stopName_s: "大道村",
    stopName_e: "Tai Tao Tsuen",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.43653300",
    longitude: "114.00211500",
  },
  {
    stopId: "2",
    stopName_c: "梅窩熟食市場",
    stopName_s: "梅窝熟食市场",
    stopName_e: "Mui Wo Cooked Food Market",
    stopLocation_c: "銀礦灣道",
    stopLocation_s: "银矿湾道",
    stopLocation_e: "Ngan Kwong Wan Road",
    latitude: "22.26614300",
    longitude: "114.00004900",
  },
  {
    stopId: "20",
    stopName_c: "長沙警署",
    stopName_s: "长沙警署",
    stopName_e: "Cheung Sha Police Headquarters",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23377200",
    longitude: "113.96021100",
  },
  {
    stopId: "200",
    stopName_c: "洪水橋輕鐵站",
    stopName_s: "洪水桥轻铁站",
    stopName_e: "Hung Shui Kiu LTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.43351800",
    longitude: "113.99781500",
  },
  {
    stopId: "201",
    stopName_c: "鍾屋村輕鐵站",
    stopName_s: "钟屋村轻铁站",
    stopName_e: "Chung Uk Tsuen LTR Station",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.42958700",
    longitude: "113.99258700",
  },
  {
    stopId: "203",
    stopName_c: "天水圍 (天慈邨)",
    stopName_s: "天水围 (天慈邨)",
    stopName_e: "Tin Shui Wai (Tin Tsz Estate)",
    stopLocation_c: "天喜街",
    stopLocation_s: "天喜街",
    stopLocation_e: "Tin Hei Street",
    latitude: "22.45353600",
    longitude: "114.00711100",
  },
  {
    stopId: "205",
    stopName_c: "天瑞邨",
    stopName_s: "天瑞邨",
    stopName_e: "Tin Shui Estate",
    stopLocation_c: "天瑞路",
    stopLocation_s: "天瑞路",
    stopLocation_e: "Tin Shui Road",
    latitude: "22.45659700",
    longitude: "113.99943400",
  },
  {
    stopId: "206",
    stopName_c: "天水圍公園",
    stopName_s: "天水围公园",
    stopName_e: "Tin Shui Wai Park",
    stopLocation_c: "天瑞路",
    stopLocation_s: "天瑞路",
    stopLocation_e: "Tin Shui Road",
    latitude: "22.45455500",
    longitude: "114.00305500",
  },
  {
    stopId: "207",
    stopName_c: "天盛苑",
    stopName_s: "天盛苑",
    stopName_e: "Tin Shing Court",
    stopLocation_c: "屏廈路",
    stopLocation_s: "屏厦路",
    stopLocation_e: "Ping Ha Road",
    latitude: "22.44669700",
    longitude: "114.00300000",
  },
  {
    stopId: "21",
    stopName_c: "長沙下村",
    stopName_s: "长沙下村",
    stopName_e: "Cheung Sha Ha Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23478700",
    longitude: "113.95723200",
  },
  {
    stopId: "22",
    stopName_c: "長沙消防局",
    stopName_s: "长沙消防局",
    stopName_e: "Cheung Sha Fire Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23663200",
    longitude: "113.95434900",
  },
  {
    stopId: "221",
    stopName_c: "大澳",
    stopName_s: "大澳",
    stopName_e: "Tai O",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.25278300",
    longitude: "113.86216000",
  },
  {
    stopId: "222",
    stopName_c: "龍田邨",
    stopName_s: "龙田邨",
    stopName_e: "Lung Tin Estate",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.25252100",
    longitude: "113.86500500",
  },
  {
    stopId: "224",
    stopName_c: "坑尾",
    stopName_s: "坑尾",
    stopName_e: "Hang Mei",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.25083200",
    longitude: "113.86930600",
  },
  {
    stopId: "225",
    stopName_c: "靈隱寺",
    stopName_s: "灵隐寺",
    stopName_e: "Ling Yan Monastery",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24428700",
    longitude: "113.87510700",
  },
  {
    stopId: "226",
    stopName_c: "新鳳村",
    stopName_s: "新凤村",
    stopName_e: "Sun Fung Tsuen",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24390000",
    longitude: "113.87700600",
  },
  {
    stopId: "227",
    stopName_c: "羌山管理站",
    stopName_s: "羌山管理站",
    stopName_e: "Keung Shan Management Centre",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24218200",
    longitude: "113.87905100",
  },
  {
    stopId: "228",
    stopName_c: "龍仔",
    stopName_s: "龙仔",
    stopName_e: "Lung Chai",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24137000",
    longitude: "113.88139200",
  },
  {
    stopId: "229",
    stopName_c: "成輝果園",
    stopName_s: "成辉果园",
    stopName_e: "Shing Fai Orchard",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24400100",
    longitude: "113.88399500",
  },
  {
    stopId: "23",
    stopName_c: "麗濱別墅",
    stopName_s: "丽滨别墅",
    stopName_e: "Leyburn Villas",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23621700",
    longitude: "113.95191600",
  },
  {
    stopId: "230",
    stopName_c: "三緣精舍",
    stopName_s: "三缘精舍",
    stopName_e: "Sam Yuen Ching Shea",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24671100",
    longitude: "113.88596800",
  },
  {
    stopId: "232",
    stopName_c: "法華苑",
    stopName_s: "法华苑",
    stopName_e: "Fat Hwa Yuen",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24622100",
    longitude: "113.88887200",
  },
  {
    stopId: "233",
    stopName_c: "深屈道",
    stopName_s: "深屈道",
    stopName_e: "Sham Wat Road",
    stopLocation_c: "深屈道",
    stopLocation_s: "深屈道",
    stopLocation_e: "Sham Wat Road",
    latitude: "22.24459200",
    longitude: "113.89187900",
  },
  {
    stopId: "234",
    stopName_c: "石壁坳引水道通道",
    stopName_s: "石壁坳引水道通道",
    stopName_e: "Shek Pik Au W.W.O. Access Road",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.23917900",
    longitude: "113.89397500",
  },
  {
    stopId: "235",
    stopName_c: "沙咀",
    stopName_s: "沙咀",
    stopName_e: "Sha Tsui",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.22850300",
    longitude: "113.89110500",
  },
  {
    stopId: "236",
    stopName_c: "石壁警崗",
    stopName_s: "石壁警岗",
    stopName_e: "Shek Pik Police Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22611900",
    longitude: "113.89813400",
  },
  {
    stopId: "237",
    stopName_c: "水口直升機場",
    stopName_s: "水口直升机场",
    stopName_e: "Shui Hau Helicopter Landing Field",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22370300",
    longitude: "113.90832500",
  },
  {
    stopId: "238",
    stopName_c: "四眼馬",
    stopName_s: "四眼马",
    stopName_e: "Four-Eye Ma",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22205400",
    longitude: "113.91063200",
  },
  {
    stopId: "239",
    stopName_c: "水口村",
    stopName_s: "水口村",
    stopName_e: "Shui Hau Village",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22110100",
    longitude: "113.91417300",
  },
  {
    stopId: "24",
    stopName_c: "蝶崗",
    stopName_s: "蝶岗",
    stopName_e: "Butterfly Crest",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23454000",
    longitude: "113.94884100",
  },
  {
    stopId: "240",
    stopName_c: "水口村(東)",
    stopName_s: "水口村(东)",
    stopName_e: "Shui Hau Village (East)",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22184100",
    longitude: "113.91576300",
  },
  {
    stopId: "241",
    stopName_c: "下橫壟",
    stopName_s: "下横垄",
    stopName_e: "Lower Wan Lung",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22205000",
    longitude: "113.91923400",
  },
  {
    stopId: "242",
    stopName_c: "上橫壟",
    stopName_s: "上横垄",
    stopName_e: "Upper Wan Lung",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22435800",
    longitude: "113.92107700",
  },
  {
    stopId: "243",
    stopName_c: "南大嶼山海底電纜站",
    stopName_s: "南大屿山海底电缆站",
    stopName_e: "South Lantau Sea Cable Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22588300",
    longitude: "113.92718000",
  },
  {
    stopId: "244",
    stopName_c: "麻埔坪道口",
    stopName_s: "麻埔坪道口",
    stopName_e: "Ma Po Ping Road Junction",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22658300",
    longitude: "113.93007700",
  },
  {
    stopId: "245",
    stopName_c: "塘福村",
    stopName_s: "塘福村",
    stopName_e: "Tong Fuk Village",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22776300",
    longitude: "113.93239700",
  },
  {
    stopId: "246",
    stopName_c: "塘福海灘",
    stopName_s: "塘福海滩",
    stopName_e: "Tong Fuk Beach",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22894100",
    longitude: "113.93594400",
  },
  {
    stopId: "247",
    stopName_c: "上長沙海灘",
    stopName_s: "上长沙海滩",
    stopName_e: "Upper Cheung Sha Beach",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23132900",
    longitude: "113.94176600",
  },
  {
    stopId: "248",
    stopName_c: "長沙大橋",
    stopName_s: "长沙大桥",
    stopName_e: "Cheung Sha Bridge",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23397900",
    longitude: "113.94736600",
  },
  {
    stopId: "249",
    stopName_c: "蝶崗",
    stopName_s: "蝶岗",
    stopName_e: "Butterfly Crest",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23506200",
    longitude: "113.94929800",
  },
  {
    stopId: "25",
    stopName_c: "長沙大橋",
    stopName_s: "长沙大桥",
    stopName_e: "Cheung Sha Bridge",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23338900",
    longitude: "113.94697700",
  },
  {
    stopId: "250",
    stopName_c: "麗濱別墅",
    stopName_s: "丽滨别墅",
    stopName_e: "Leyburn Villas",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23647200",
    longitude: "113.95142400",
  },
  {
    stopId: "251",
    stopName_c: "長沙消防局",
    stopName_s: "长沙消防局",
    stopName_e: "Cheung Sha Fire Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23680300",
    longitude: "113.95543400",
  },
  {
    stopId: "252",
    stopName_c: "長沙下村",
    stopName_s: "长沙下村",
    stopName_e: "Cheung Sha Ha Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23496500",
    longitude: "113.95717000",
  },
  {
    stopId: "253",
    stopName_c: "長沙警署",
    stopName_s: "长沙警署",
    stopName_e: "Cheung Sha Police Headquarters",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23396400",
    longitude: "113.96017400",
  },
  {
    stopId: "254",
    stopName_c: "長沙上村",
    stopName_s: "长沙上村",
    stopName_e: "Cheung Sha Sheung Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23533000",
    longitude: "113.96154700",
  },
  {
    stopId: "255",
    stopName_c: "散石灣迴旋處",
    stopName_s: "散石湾回旋处",
    stopName_e: "San Shek Wan Roundabout",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23672700",
    longitude: "113.96242400",
  },
  {
    stopId: "256",
    stopName_c: "女青年會梁紹榮度假村",
    stopName_s: "女青年会梁绍荣度假村",
    stopName_e: "YWCA Sydney Leong Holiday Lodge",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23776800",
    longitude: "113.96397300",
  },
  {
    stopId: "257",
    stopName_c: "散石灣村",
    stopName_s: "散石湾村",
    stopName_e: "San Shek Wan Village",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23902400",
    longitude: "113.96652600",
  },
  {
    stopId: "258",
    stopName_c: "散石灣中蘆",
    stopName_s: "散石湾中芦",
    stopName_e: "San Shek Wan 3 1/4 Milestone",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24125500",
    longitude: "113.96866600",
  },
  {
    stopId: "259",
    stopName_c: "羅屋村",
    stopName_s: "罗屋村",
    stopName_e: "Lo Uk Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24337500",
    longitude: "113.97483200",
  },
  {
    stopId: "26",
    stopName_c: "上長沙海灘",
    stopName_s: "上长沙海滩",
    stopName_e: "Upper Cheung Sha Beach",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23087700",
    longitude: "113.94152500",
  },
  {
    stopId: "260",
    stopName_c: "新圍村",
    stopName_s: "新围村",
    stopName_e: "Sun Wai Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24347600",
    longitude: "113.97732200",
  },
  {
    stopId: "261",
    stopName_c: "老圍村",
    stopName_s: "老围村",
    stopName_e: "Lo Wai Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24444000",
    longitude: "113.97900000",
  },
  {
    stopId: "262",
    stopName_c: "貝澳油站",
    stopName_s: "贝澳油站",
    stopName_e: "Pui O Petrol Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.24750100",
    longitude: "113.98077000",
  },
  {
    stopId: "263",
    stopName_c: "太古職員宿舍",
    stopName_s: "太古职员宿舍",
    stopName_e: "Swire Staff Holiday House",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.25212000",
    longitude: "113.98474500",
  },
  {
    stopId: "264",
    stopName_c: "南山營地",
    stopName_s: "南山营地",
    stopName_e: "Nam Shan Camp Site",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.25606700",
    longitude: "113.98747000",
  },
  {
    stopId: "265",
    stopName_c: "南山三屋村",
    stopName_s: "南山三屋村",
    stopName_e: "Nam Shan Sam Uk Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.25732700",
    longitude: "113.98990100",
  },
  {
    stopId: "266",
    stopName_c: "荔枝園",
    stopName_s: "荔枝园",
    stopName_e: "Lai Chi Yuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.26066700",
    longitude: "113.99626800",
  },
  {
    stopId: "269",
    stopName_c: "深屈道口",
    stopName_s: "深屈道口",
    stopName_e: "Sham Wat Road Junction",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24520700",
    longitude: "113.89208900",
  },
  {
    stopId: "27",
    stopName_c: "塘福海灘",
    stopName_s: "塘福海滩",
    stopName_e: "Tong Fuk Beach",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22850900",
    longitude: "113.93533900",
  },
  {
    stopId: "270",
    stopName_c: "昂坪",
    stopName_s: "昂坪",
    stopName_e: "Ngong Ping",
    stopLocation_c: "寶昂路",
    stopLocation_s: "宝昂路",
    stopLocation_e: "Po Ngong Road",
    latitude: "22.25561200",
    longitude: "113.90286200",
  },
  {
    stopId: "271",
    stopName_c: "山海亭",
    stopName_s: "山海亭",
    stopName_e: "San Hoi Ting",
    stopLocation_c: "深屈道",
    stopLocation_s: "深屈道",
    stopLocation_e: "Sham Wat Road",
    latitude: "22.24931300",
    longitude: "113.89284000",
  },
  {
    stopId: "273",
    stopName_c: "長沙引水道",
    stopName_s: "长沙引水道",
    stopName_e: "Cheung Sha Catchwater",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.24000700",
    longitude: "113.95733900",
  },
  {
    stopId: "274",
    stopName_c: "國泰城",
    stopName_s: "国泰城",
    stopName_e: "Cathay City",
    stopLocation_c: "觀景路",
    stopLocation_s: "观景路",
    stopLocation_e: "Scenic Road",
    latitude: "22.29755500",
    longitude: "113.93336000",
  },
  {
    stopId: "276",
    stopName_c: "赤鱲角南路",
    stopName_s: "赤鱲角南路",
    stopName_e: "Chek Lap Kok South Road",
    stopLocation_c: "赤鱲角南路",
    stopLocation_s: "赤鱲角南路",
    stopLocation_e: "Chek Lap Kok South Road",
    latitude: "22.29197000",
    longitude: "113.92875900",
  },
  {
    stopId: "277",
    stopName_c: "飛機燃料庫",
    stopName_s: "飞机燃料库",
    stopName_e: "Aviation Fuel Tank Farm",
    stopLocation_c: "觀景路",
    stopLocation_s: "观景路",
    stopLocation_e: "Scenic Road",
    latitude: "22.29307500",
    longitude: "113.93222900",
  },
  {
    stopId: "278",
    stopName_c: "東涌站巴士總站",
    stopName_s: "东涌站巴士总站",
    stopName_e: "Tung Chung Station Bus Terminus",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.28986200",
    longitude: "113.93961600",
  },
  {
    stopId: "279",
    stopName_c: "上嶺皮",
    stopName_s: "上岭皮",
    stopName_e: "Sheung Ling Pei",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27879200",
    longitude: "113.93714800",
  },
  {
    stopId: "28",
    stopName_c: "塘福村",
    stopName_s: "塘福村",
    stopName_e: "Tong Fuk Village",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22756500",
    longitude: "113.93270600",
  },
  {
    stopId: "280",
    stopName_c: "下嶺皮",
    stopName_s: "下岭皮",
    stopName_e: "Ha Ling Pei",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27851200",
    longitude: "113.93542300",
  },
  {
    stopId: "282",
    stopName_c: "黃家圍",
    stopName_s: "黄家围",
    stopName_e: "Wong Ka Wai",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27703800",
    longitude: "113.93397500",
  },
  {
    stopId: "283",
    stopName_c: "龍井頭",
    stopName_s: "龙井头",
    stopName_e: "Lung Tseng Tau",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27570700",
    longitude: "113.93370700",
  },
  {
    stopId: "284",
    stopName_c: "石門甲道",
    stopName_s: "石门甲道",
    stopName_e: "Shek Mun Kap Road",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27047000",
    longitude: "113.93446500",
  },
  {
    stopId: "286",
    stopName_c: "十八區墳場",
    stopName_s: "十八区坟场",
    stopName_e: "Cemetery Area No. 18",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.26567800",
    longitude: "113.93674000",
  },
  {
    stopId: "287",
    stopName_c: "東涌坳管理站",
    stopName_s: "东涌坳管理站",
    stopName_e: "Tung Chung Au Management Centre",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.26410400",
    longitude: "113.93755200",
  },
  {
    stopId: "288",
    stopName_c: "伯公坳",
    stopName_s: "伯公坳",
    stopName_e: "Pak Kung Au",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.24893900",
    longitude: "113.94259700",
  },
  {
    stopId: "289",
    stopName_c: "逸東邨",
    stopName_s: "逸东邨",
    stopName_e: "Yat Tung Estate",
    stopLocation_c: "逸東街",
    stopLocation_s: "逸东街",
    stopLocation_e: "Yat Tung Street",
    latitude: "22.28205300",
    longitude: "113.93586200",
  },
  {
    stopId: "291",
    stopName_c: "石門甲",
    stopName_s: "石门甲",
    stopName_e: "Shek Mun Kap",
    stopLocation_c: "石門甲道",
    stopLocation_s: "石门甲道",
    stopLocation_e: "Shek Mun Kap Road",
    latitude: "22.26905700",
    longitude: "113.93118500",
  },
  {
    stopId: "292",
    stopName_c: "石門甲村",
    stopName_s: "石门甲村",
    stopName_e: "Shek Mun Kap Village",
    stopLocation_c: "石門甲道",
    stopLocation_s: "石门甲道",
    stopLocation_e: "Shek Mun Kap Road",
    latitude: "22.26957500",
    longitude: "113.93197800",
  },
  {
    stopId: "293",
    stopName_c: "小蠔灣",
    stopName_s: "小蚝湾",
    stopName_e: "Siu Ho Wan",
    stopLocation_c: "深豐路",
    stopLocation_s: "深丰路",
    stopLocation_e: "Shum Fung Road",
    latitude: "22.31551900",
    longitude: "113.99797500",
  },
  {
    stopId: "294",
    stopName_c: "政府維修廠",
    stopName_s: "政府维修厂",
    stopName_e: "Government Maintenance Depot",
    stopLocation_c: "翔東路",
    stopLocation_s: "翔东路",
    stopLocation_e: "Cheung Tung Road",
    latitude: "22.30928300",
    longitude: "113.98925400",
  },
  {
    stopId: "295",
    stopName_c: "白芒",
    stopName_s: "白芒",
    stopName_e: "Pak Mong",
    stopLocation_c: "翔東路",
    stopLocation_s: "翔东路",
    stopLocation_e: "Cheung Tung Road",
    latitude: "22.29796400",
    longitude: "113.96758000",
  },
  {
    stopId: "297",
    stopName_c: "迎東邨",
    stopName_s: "迎东邨",
    stopName_e: "Ying Tung Estate",
    stopLocation_c: "迎東邨",
    stopLocation_s: "迎东邨",
    stopLocation_e: "Ying Tung Estate",
    latitude: "22.29710400",
    longitude: "113.95334200",
  },
  {
    stopId: "298",
    stopName_c: "映灣園二期",
    stopName_s: "映湾园二期",
    stopName_e: "Caribbean Coast Phase 2",
    stopLocation_c: "文東路",
    stopLocation_s: "文东路",
    stopLocation_e: "Man Tung Road",
    latitude: "22.29193200",
    longitude: "113.95049000",
  },
  {
    stopId: "299",
    stopName_c: "海堤灣畔",
    stopName_s: "海堤湾畔",
    stopName_e: "Seaview Crescent",
    stopLocation_c: "惠東路",
    stopLocation_s: "惠东路",
    stopLocation_e: "Wai Tung Road",
    latitude: "22.29303900",
    longitude: "113.94317900",
  },
  {
    stopId: "3",
    stopName_c: "銀灣邨",
    stopName_s: "银湾邨",
    stopName_e: "Ngan Wan Estate",
    stopLocation_c: "銀礦灣道",
    stopLocation_s: "银矿湾道",
    stopLocation_e: "Ngan Kwong Wan Road",
    latitude: "22.26540600",
    longitude: "113.99707400",
  },
  {
    stopId: "30",
    stopName_c: "麻埔坪村",
    stopName_s: "麻埔坪村",
    stopName_e: "Ma Po Ping Village",
    stopLocation_c: "麻埔坪道",
    stopLocation_s: "麻埔坪道",
    stopLocation_e: "Ma Po Ping Road",
    latitude: "22.22992600",
    longitude: "113.92805000",
  },
  {
    stopId: "302",
    stopName_c: "尚城",
    stopName_s: "尚城",
    stopName_e: "Uptown",
    stopLocation_c: "青山公路",
    stopLocation_s: "青山公路",
    stopLocation_e: "Castle Peak Road",
    latitude: "22.43530000",
    longitude: "114.00031400",
  },
  {
    stopId: "303",
    stopName_c: "東環",
    stopName_s: "东环",
    stopName_e: "Century Link",
    stopLocation_c: "迎康街6號",
    stopLocation_s: "迎康街6号",
    stopLocation_e: "Ying Hong Street No.6",
    latitude: "22.29439800",
    longitude: "113.94907100",
  },
  {
    stopId: "305",
    stopName_c: "梅窩碼頭",
    stopName_s: "梅窝码头",
    stopName_e: "Mui Wo Ferry Pier",
    stopLocation_c: "梅窩碼頭",
    stopLocation_s: "梅窝码头",
    stopLocation_e: "Mui Wo Ferry Pier",
    latitude: "22.26466400",
    longitude: "114.00155400",
  },
  {
    stopId: "306",
    stopName_c: "逸東邨雍逸樓",
    stopName_s: "逸东邨雍逸楼",
    stopName_e: "Yung Yat House, Yat Tung Estate",
    stopLocation_c: "裕東路",
    stopLocation_s: "裕东路",
    stopLocation_e: "Yu Tung Road",
    latitude: "22.27974400",
    longitude: "113.93699500",
  },
  {
    stopId: "307",
    stopName_c: "大橋香港口岸",
    stopName_s: "大桥香港口岸",
    stopName_e: "HZMB Hong Kong Port",
    stopLocation_c: "大橋香港口岸 (抵港層)",
    stopLocation_s: "大桥香港口岸 (抵港层)",
    stopLocation_e: "HZMB Hong Kong Port (Arrival Level)",
    latitude: "22.31640000",
    longitude: "113.95085600",
  },
  {
    stopId: "308",
    stopName_c: "大橋香港口岸旅檢大樓",
    stopName_s: "大桥香港口岸旅检大楼",
    stopName_e: "HZMB Hong Kong Port Passenger Clearance Building",
    stopLocation_c: "大橋香港口岸",
    stopLocation_s: "大桥香港口岸",
    stopLocation_e: "HZMB Hong Kong Port",
    latitude: "22.31721100",
    longitude: "113.95053100",
  },
  {
    stopId: "309",
    stopName_c: "滿東邨",
    stopName_s: "满东邨",
    stopName_e: "Mun Tung Estate",
    stopLocation_c: "裕東路",
    stopLocation_s: "裕东路",
    stopLocation_e: "Yu Tung Road",
    latitude: "22.27865300",
    longitude: "113.93320300",
  },
  {
    stopId: "31",
    stopName_c: "麻埔坪道口",
    stopName_s: "麻埔坪道口",
    stopName_e: "Ma Po Ping Road Junction",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22601800",
    longitude: "113.92949500",
  },
  {
    stopId: "310",
    stopName_c: "滿東邨",
    stopName_s: "满东邨",
    stopName_e: "Mun Tung Estate",
    stopLocation_c: "裕東路",
    stopLocation_s: "裕东路",
    stopLocation_e: "Yu Tung Road",
    latitude: "22.27892200",
    longitude: "113.93455600",
  },
  {
    stopId: "311",
    stopName_c: "機場博覽館",
    stopName_s: "机场博览馆",
    stopName_e: "AsiaWorld-Expo",
    stopLocation_c: "機場博覽館",
    stopLocation_s: "机场博览馆",
    stopLocation_e: "AsiaWorld-Expo",
    latitude: "22.31932300",
    longitude: "113.94044600",
  },
  {
    stopId: "312",
    stopName_c: "香港天際萬豪酒店",
    stopName_s: "香港天际万豪酒店",
    stopName_e: "Hong Kong SkyCity Marriott Hotel",
    stopLocation_c: "航天城東路",
    stopLocation_s: "航天城东路",
    stopLocation_e: "Sky City Road East",
    latitude: "22.31777700",
    longitude: "113.94331700",
  },
  {
    stopId: "313",
    stopName_c: "大橋香港口岸",
    stopName_s: "大桥香港口岸",
    stopName_e: "HZMB Hong Kong Port",
    stopLocation_c: "大橋香港口岸 (抵港層)",
    stopLocation_s: "大桥香港口岸 (抵港层)",
    stopLocation_e: "HZMB Hong Kong Port (Arrival Level)",
    latitude: "22.31640000",
    longitude: "113.95085600",
  },
  {
    stopId: "315",
    stopName_c: "映灣園",
    stopName_s: "映湾园",
    stopName_e: "Caribbean Coast",
    stopLocation_c: "映灣園",
    stopLocation_s: "映湾园",
    stopLocation_e: "Caribbean Coast",
    latitude: "22.29322200",
    longitude: "113.94941000",
  },
  {
    stopId: "317",
    stopName_c: "東涌達東路巴士總站",
    stopName_s: "东涌达东路巴士总站",
    stopName_e: "Tung Chung Tat Tung Road Bus Terminus",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.29058000",
    longitude: "113.93935200",
  },
  {
    stopId: "318",
    stopName_c: "東涌達東路巴士總站",
    stopName_s: "东涌达东路巴士总站",
    stopName_e: "Tung Chung Tat Tung Road Bus Terminus",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.29058000",
    longitude: "113.93935200",
  },
  {
    stopId: "319",
    stopName_c: "東涌發展碼頭",
    stopName_s: "东涌发展码头",
    stopName_e: "Tung Chung Development Ferry Pier",
    stopLocation_c: "東涌海濱路",
    stopLocation_s: "东涌海滨路",
    stopLocation_e: "Tung Chung Waterfront Road",
    latitude: "22.29384600",
    longitude: "113.94044900",
  },
  {
    stopId: "32",
    stopName_c: "塘福懲教所",
    stopName_s: "塘福惩教所",
    stopName_e: "Tong Fuk Correctional Institution",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22876400",
    longitude: "113.92608400",
  },
  {
    stopId: "320",
    stopName_c: "北大嶼山醫院(北行), 逸東邨美逸樓",
    stopName_s: "北大屿山医院(北行), 逸东邨美逸楼",
    stopName_e:
      "North Lantau Hospital (North Bound), Mei Yat House Yat Tung Estate",
    stopLocation_c: "松仁路",
    stopLocation_s: "松仁路",
    stopLocation_e: "Chung Yan Road",
    latitude: "22.28129500",
    longitude: "113.93882200",
  },
  {
    stopId: "321",
    stopName_c: "東涌纜車站",
    stopName_s: "东涌缆车站",
    stopName_e: "Tung Chung Cable Car Terminal",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.28930100",
    longitude: "113.93873300",
  },
  {
    stopId: "322",
    stopName_c: "北大嶼山醫院(南行)",
    stopName_s: "北大屿山医院(南行)",
    stopName_e: "North Lantau Hospital (South Bound)",
    stopLocation_c: "松仁路",
    stopLocation_s: "松仁路",
    stopLocation_e: "Chung Yan Road",
    latitude: "22.28186100",
    longitude: "113.93880300",
  },
  {
    stopId: "324",
    stopName_c: "裕雅苑",
    stopName_s: "裕雅苑",
    stopName_e: "Yu Nga Court",
    stopLocation_c: "迎禧路",
    stopLocation_s: "迎禧路",
    stopLocation_e: "Ying Hei Road",
    latitude: "22.29419400",
    longitude: "113.94725400",
  },
  {
    stopId: "327",
    stopName_c: "迪士尼樂園",
    stopName_s: "迪士尼乐园",
    stopName_e: "Disneyland",
    stopLocation_c: "幻想道",
    stopLocation_s: "幻想道",
    stopLocation_e: "Fantasy Road",
    latitude: "22.31635600",
    longitude: "114.04573200",
  },
  {
    stopId: "328",
    stopName_c: "迪士尼樂園",
    stopName_s: "迪士尼乐园",
    stopName_e: "Disneyland",
    stopLocation_c: "幻想道",
    stopLocation_s: "幻想道",
    stopLocation_e: "Fantasy Road",
    latitude: "22.31635600",
    longitude: "114.04573200",
  },
  {
    stopId: "329",
    stopName_c: "裕雅苑",
    stopName_s: "裕雅苑",
    stopName_e: "Yu Nga Court",
    stopLocation_c: "怡東路",
    stopLocation_s: "怡东路",
    stopLocation_e: "Yi Tung Road",
    latitude: "22.29655000",
    longitude: "113.94846500",
  },
  {
    stopId: "33",
    stopName_c: "上橫壟",
    stopName_s: "上横垄",
    stopName_e: "Upper Wan Lung",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22334800",
    longitude: "113.92062400",
  },
  {
    stopId: "330",
    stopName_c: "裕雅商場",
    stopName_s: "裕雅商场",
    stopName_e: "Yu Nga Shopping Mall",
    stopLocation_c: "怡東路",
    stopLocation_s: "怡东路",
    stopLocation_e: "Yi Tung Road",
    latitude: "22.29542600",
    longitude: "113.94672800",
  },
  {
    stopId: "34",
    stopName_c: "下橫壟",
    stopName_s: "下横垄",
    stopName_e: "Lower Wan Lung",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22230500",
    longitude: "113.91974100",
  },
  {
    stopId: "35",
    stopName_c: "水口村(東)",
    stopName_s: "水口村(东)",
    stopName_e: "Shui Hau Village (East)",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22156500",
    longitude: "113.91605900",
  },
  {
    stopId: "36",
    stopName_c: "水口村",
    stopName_s: "水口村",
    stopName_e: "Shui Hau Village",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22098931",
    longitude: "113.91431800",
  },
  {
    stopId: "37",
    stopName_c: "四眼馬",
    stopName_s: "四眼马",
    stopName_e: "Four-Eye Ma",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22191300",
    longitude: "113.91037000",
  },
  {
    stopId: "38",
    stopName_c: "水口直升機場",
    stopName_s: "水口直升机场",
    stopName_e: "Shui Hau Helicopter Landing Field",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22353200",
    longitude: "113.90806300",
  },
  {
    stopId: "39",
    stopName_c: "石壁警崗",
    stopName_s: "石壁警岗",
    stopName_e: "Shek Pik Police Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.22586200",
    longitude: "113.89772000",
  },
  {
    stopId: "4",
    stopName_c: "梅窩街市",
    stopName_s: "梅窝街市",
    stopName_e: "Mui Wo Market",
    stopLocation_c: "銀石街",
    stopLocation_s: "银石街",
    stopLocation_e: "Ngan Shek Street",
    latitude: "22.26675900",
    longitude: "113.99699900",
  },
  {
    stopId: "40",
    stopName_c: "沙咀懲教所",
    stopName_s: "沙咀惩教所",
    stopName_e: "Sha Tsui Detention Centre",
    stopLocation_c: "石壁水塘道",
    stopLocation_s: "石壁水塘道",
    stopLocation_e: "Shek Pik Reservoir Road",
    latitude: "22.22496900",
    longitude: "113.89348700",
  },
  {
    stopId: "41",
    stopName_c: "沙咀",
    stopName_s: "沙咀",
    stopName_e: "Sha Tsui",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.22832800",
    longitude: "113.89060000",
  },
  {
    stopId: "42",
    stopName_c: "石壁坳引水道通道",
    stopName_s: "石壁坳引水道通道",
    stopName_e: "Shek Pik Au W.W.O. Access Road",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.23945100",
    longitude: "113.89369700",
  },
  {
    stopId: "43",
    stopName_c: "深屈道口",
    stopName_s: "深屈道口",
    stopName_e: "Sham Wat Road Junction",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24503800",
    longitude: "113.89223700",
  },
  {
    stopId: "44",
    stopName_c: "法華苑",
    stopName_s: "法华苑",
    stopName_e: "Fat Hwa Yuen",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24612200",
    longitude: "113.88904200",
  },
  {
    stopId: "45",
    stopName_c: "三緣精舍",
    stopName_s: "三缘精舍",
    stopName_e: "Sam Yuen Ching Shea",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24643500",
    longitude: "113.88624200",
  },
  {
    stopId: "46",
    stopName_c: "成輝果園",
    stopName_s: "成辉果园",
    stopName_e: "Shing Fai Orchard",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24382000",
    longitude: "113.88420900",
  },
  {
    stopId: "47",
    stopName_c: "觀音寺",
    stopName_s: "观音寺",
    stopName_e: "Kwun Yam Monastery",
    stopLocation_c: "姜山道",
    stopLocation_s: "姜山道",
    stopLocation_e: "Keung Shan Road",
    latitude: "22.24225600",
    longitude: "113.88299100",
  },
  {
    stopId: "48",
    stopName_c: "龍仔",
    stopName_s: "龙仔",
    stopName_e: "Lung Chai",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24081600",
    longitude: "113.88102200",
  },
  {
    stopId: "49",
    stopName_c: "羌山管理站",
    stopName_s: "羌山管理站",
    stopName_e: "Keung Shan Management Centre",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24203200",
    longitude: "113.87882300",
  },
  {
    stopId: "5",
    stopName_c: "銀景中心",
    stopName_s: "银景中心",
    stopName_e: "Ngan King Centre",
    stopLocation_c: "銀礦灣道",
    stopLocation_s: "银矿湾道",
    stopLocation_e: "Ngan Kwong Wan Road",
    latitude: "22.26553700",
    longitude: "113.99696500",
  },
  {
    stopId: "51",
    stopName_c: "靈隱寺",
    stopName_s: "灵隐寺",
    stopName_e: "Ling Yan Monastery",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24401800",
    longitude: "113.87500900",
  },
  {
    stopId: "52",
    stopName_c: "坑尾",
    stopName_s: "坑尾",
    stopName_e: "Hang Mei",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.25065600",
    longitude: "113.86906200",
  },
  {
    stopId: "53",
    stopName_c: "佛教筏可紀念中學",
    stopName_s: "佛教筏可纪念中学",
    stopName_e: "Buddhist Fat Ho Memorial College",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.25203300",
    longitude: "113.86698800",
  },
  {
    stopId: "54",
    stopName_c: "龍田邨",
    stopName_s: "龙田邨",
    stopName_e: "Lung Tin Estate",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.25232600",
    longitude: "113.86497600",
  },
  {
    stopId: "55",
    stopName_c: "大澳",
    stopName_s: "大澳",
    stopName_e: "Tai O",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.25278300",
    longitude: "113.86216000",
  },
  {
    stopId: "56",
    stopName_c: "禮智園墳場",
    stopName_s: "礼智园坟场",
    stopName_e: "Lai Chi Yuen Cemetery",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.25932700",
    longitude: "113.99399300",
  },
  {
    stopId: "57",
    stopName_c: "梅窩警署",
    stopName_s: "梅窝警署",
    stopName_e: "Mui Wo Police Station",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.26409300",
    longitude: "113.99890600",
  },
  {
    stopId: "58",
    stopName_c: "深屈道",
    stopName_s: "深屈道",
    stopName_e: "Sham Wat Road",
    stopLocation_c: "深屈道",
    stopLocation_s: "深屈道",
    stopLocation_e: "Sham Wat Road",
    latitude: "22.24505400",
    longitude: "113.89119300",
  },
  {
    stopId: "59",
    stopName_c: "山海亭",
    stopName_s: "山海亭",
    stopName_e: "San Hoi Ting",
    stopLocation_c: "深屈道",
    stopLocation_s: "深屈道",
    stopLocation_e: "Sham Wat Road",
    latitude: "22.24947700",
    longitude: "113.89305300",
  },
  {
    stopId: "6",
    stopName_c: "銀鑛灣濾水廠",
    stopName_s: "银鑛湾滤水厂",
    stopName_e: "Silver Mine Bay Water Treatment Works",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.26296600",
    longitude: "113.99782600",
  },
  {
    stopId: "60",
    stopName_c: "昂坪市集",
    stopName_s: "昂坪市集",
    stopName_e: "Ngong Ping Village",
    stopLocation_c: "昂坪道",
    stopLocation_s: "昂坪道",
    stopLocation_e: "Ngong Ping Road",
    latitude: "22.25546100",
    longitude: "113.90398100",
  },
  {
    stopId: "62",
    stopName_c: "昂坪",
    stopName_s: "昂坪",
    stopName_e: "Ngong Ping",
    stopLocation_c: "寶昂路",
    stopLocation_s: "宝昂路",
    stopLocation_e: "Po Ngong Road",
    latitude: "22.25561200",
    longitude: "113.90286200",
  },
  {
    stopId: "64",
    stopName_c: "長沙引水道",
    stopName_s: "长沙引水道",
    stopName_e: "Cheung Sha Catchwater",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.23981400",
    longitude: "113.95721600",
  },
  {
    stopId: "65",
    stopName_c: "伯公坳",
    stopName_s: "伯公坳",
    stopName_e: "Pak Kung Au",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.24805400",
    longitude: "113.94313900",
  },
  {
    stopId: "66",
    stopName_c: "東涌坳管理站",
    stopName_s: "东涌坳管理站",
    stopName_e: "Tung Chung Au Management Centre",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.26400600",
    longitude: "113.93715500",
  },
  {
    stopId: "67",
    stopName_c: "十八區墳場",
    stopName_s: "十八区坟场",
    stopName_e: "Cemetery Area No. 18",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.26546600",
    longitude: "113.93646300",
  },
  {
    stopId: "68",
    stopName_c: "石門甲道",
    stopName_s: "石门甲道",
    stopName_e: "Shek Mun Kap Road",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.26991800",
    longitude: "113.93424300",
  },
  {
    stopId: "69",
    stopName_c: "龍井頭",
    stopName_s: "龙井头",
    stopName_e: "Lung Tseng Tau",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27597500",
    longitude: "113.93337700",
  },
  {
    stopId: "7",
    stopName_c: "荔枝園",
    stopName_s: "荔枝园",
    stopName_e: "Lai Chi Yuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.26075800",
    longitude: "113.99647700",
  },
  {
    stopId: "70",
    stopName_c: "黃家圍",
    stopName_s: "黄家围",
    stopName_e: "Wong Ka Wai",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27716200",
    longitude: "113.93381200",
  },
  {
    stopId: "71",
    stopName_c: "下嶺皮",
    stopName_s: "下岭皮",
    stopName_e: "Ha Ling Pei",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27873100",
    longitude: "113.93547500",
  },
  {
    stopId: "72",
    stopName_c: "上嶺皮",
    stopName_s: "上岭皮",
    stopName_e: "Sheung Ling Pei",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27891200",
    longitude: "113.93685600",
  },
  {
    stopId: "73",
    stopName_c: "東涌鄉事委員會",
    stopName_s: "东涌乡事委员会",
    stopName_e: "Tung Chung Rural Committee Office",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27913800",
    longitude: "113.93929900",
  },
  {
    stopId: "74",
    stopName_c: "馬灣新村",
    stopName_s: "马湾新村",
    stopName_e: "Ma Wan Sun Tsuen",
    stopLocation_c: "松仁路",
    stopLocation_s: "松仁路",
    stopLocation_e: "Chung Yan Road",
    latitude: "22.27986500",
    longitude: "113.94024300",
  },
  {
    stopId: "76",
    stopName_c: "北大嶼山醫院(南行)",
    stopName_s: "北大屿山医院(南行)",
    stopName_e: "North Lantau Hospital (South Bound)",
    stopLocation_c: "松仁路",
    stopLocation_s: "松仁路",
    stopLocation_e: "Chung Yan Road",
    latitude: "22.28186100",
    longitude: "113.93880300",
  },
  {
    stopId: "77",
    stopName_c: "東涌消防局",
    stopName_s: "东涌消防局",
    stopName_e: "Tung Chung Fire Station",
    stopLocation_c: "順東路",
    stopLocation_s: "顺东路",
    stopLocation_e: "Shun Tung Road",
    latitude: "22.28603000",
    longitude: "113.94105700",
  },
  {
    stopId: "78",
    stopName_c: "東涌纜車站",
    stopName_s: "东涌缆车站",
    stopName_e: "Tung Chung Cable Car Terminal",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.28930100",
    longitude: "113.93873300",
  },
  {
    stopId: "79",
    stopName_c: "東涌站巴士總站",
    stopName_s: "东涌站巴士总站",
    stopName_e: "Tung Chung Station Bus Terminus",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.28986200",
    longitude: "113.93961600",
  },
  {
    stopId: "8",
    stopName_c: "南山三屋村",
    stopName_s: "南山三屋村",
    stopName_e: "Nam Shan Sam Uk Tsuen",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.25707200",
    longitude: "113.99010800",
  },
  {
    stopId: "80",
    stopName_c: "富東廣場",
    stopName_s: "富东广场",
    stopName_e: "Fu Tung Plaza",
    stopLocation_c: "達東路",
    stopLocation_s: "达东路",
    stopLocation_e: "Tat Tung Road",
    latitude: "22.28887000",
    longitude: "113.94210500",
  },
  {
    stopId: "81",
    stopName_c: "裕東苑",
    stopName_s: "裕东苑",
    stopName_e: "Yu Tung Court",
    stopLocation_c: "順東路",
    stopLocation_s: "顺东路",
    stopLocation_e: "Shun Tung Road",
    latitude: "22.28607700",
    longitude: "113.94160300",
  },
  {
    stopId: "83",
    stopName_c: "散石灣迴旋處",
    stopName_s: "散石湾回旋处",
    stopName_e: "San Shek Wan Roundabout",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.23654400",
    longitude: "113.96255000",
  },
  {
    stopId: "84",
    stopName_c: "新鳳村",
    stopName_s: "新凤村",
    stopName_e: "Sun Fung Tsuen",
    stopLocation_c: "大澳道",
    stopLocation_s: "大澳道",
    stopLocation_e: "Tai O Road",
    latitude: "22.24357100",
    longitude: "113.87697200",
  },
  {
    stopId: "88",
    stopName_c: "逸東邨居逸樓",
    stopName_s: "逸东邨居逸楼",
    stopName_e: "Kui Yat House, Yat Tung Estate",
    stopLocation_c: "逸東街",
    stopLocation_s: "逸东街",
    stopLocation_e: "Yat Tung Street",
    latitude: "22.28236900",
    longitude: "113.93657600",
  },
  {
    stopId: "89",
    stopName_c: "逸東邨",
    stopName_s: "逸东邨",
    stopName_e: "Yat Tung Estate",
    stopLocation_c: "逸東街",
    stopLocation_s: "逸东街",
    stopLocation_e: "Yat Tung Street",
    latitude: "22.28205300",
    longitude: "113.93586200",
  },
  {
    stopId: "9",
    stopName_c: "南山營地",
    stopName_s: "南山营地",
    stopName_e: "Nam Shan Camp Site",
    stopLocation_c: "嶼南道",
    stopLocation_s: "屿南道",
    stopLocation_e: "South Lantau Road",
    latitude: "22.25545100",
    longitude: "113.98681100",
  },
  {
    stopId: "90",
    stopName_c: "裕泰苑",
    stopName_s: "裕泰苑",
    stopName_e: "Yu Tai Court",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.28056500",
    longitude: "113.94106400",
  },
  {
    stopId: "91",
    stopName_c: "赤立角新村",
    stopName_s: "赤立角新村",
    stopName_e: "Chek Lap Kok New Village",
    stopLocation_c: "黃龍坑道",
    stopLocation_s: "黄龙坑道",
    stopLocation_e: "Wong Lung Hang Road",
    latitude: "22.27770400",
    longitude: "113.94199600",
  },
  {
    stopId: "92",
    stopName_c: "石門甲村",
    stopName_s: "石门甲村",
    stopName_e: "Shek Mun Kap Village",
    stopLocation_c: "石門甲道",
    stopLocation_s: "石门甲道",
    stopLocation_e: "Shek Mun Kap Road",
    latitude: "22.26940400",
    longitude: "113.93199600",
  },
  {
    stopId: "93",
    stopName_c: "石門甲",
    stopName_s: "石门甲",
    stopName_e: "Shek Mun Kap",
    stopLocation_c: "石門甲道",
    stopLocation_s: "石门甲道",
    stopLocation_e: "Shek Mun Kap Road",
    latitude: "22.26905700",
    longitude: "113.93118500",
  },
  {
    stopId: "94",
    stopName_c: "東涌鄉事委員會",
    stopName_s: "东涌乡事委员会",
    stopName_e: "Tung Chung Rural Committee Office",
    stopLocation_c: "東涌道",
    stopLocation_s: "东涌道",
    stopLocation_e: "Tung Chung Road",
    latitude: "22.27893600",
    longitude: "113.93879500",
  },
  {
    stopId: "95",
    stopName_c: "小蠔灣",
    stopName_s: "小蚝湾",
    stopName_e: "Siu Ho Wan",
    stopLocation_c: "深豐路",
    stopLocation_s: "深丰路",
    stopLocation_e: "Shum Fung Road",
    latitude: "22.31551900",
    longitude: "113.99797500",
  },
  {
    stopId: "96",
    stopName_c: "小蠔灣濾水廠",
    stopName_s: "小蚝湾滤水厂",
    stopName_e: "Siu Ho Wan Water Treatment Works",
    stopLocation_c: "翔東路",
    stopLocation_s: "翔东路",
    stopLocation_e: "Cheung Tung Road",
    latitude: "22.31359500",
    longitude: "113.99573400",
  },
  {
    stopId: "97",
    stopName_c: "愉景灣隧道",
    stopName_s: "愉景湾隧道",
    stopName_e: "Discovery Bay Tunnel",
    stopLocation_c: "翔東路",
    stopLocation_s: "翔东路",
    stopLocation_e: "Cheung Tung Road",
    latitude: "22.31002200",
    longitude: "113.99058400",
  },
  {
    stopId: "98",
    stopName_c: "政府維修廠",
    stopName_s: "政府维修厂",
    stopName_e: "Government Maintenance Depot",
    stopLocation_c: "翔東路",
    stopLocation_s: "翔东路",
    stopLocation_e: "Cheung Tung Road",
    latitude: "22.30893500",
    longitude: "113.98945100",
  },
  {
    stopId: "99",
    stopName_c: "白芒",
    stopName_s: "白芒",
    stopName_e: "Pak Mong",
    stopLocation_c: "翔東路",
    stopLocation_s: "翔东路",
    stopLocation_e: "Cheung Tung Road",
    latitude: "22.29796400",
    longitude: "113.96758000",
  },
];
